"""Type stubs for franken_networkx._fnx (Rust extension module)."""

from typing import Any, Iterator, Optional, Union

__version__: str

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class NetworkXError(Exception): ...
class NetworkXPointlessConcept(NetworkXError): ...
class NetworkXAlgorithmError(NetworkXError): ...
class NetworkXUnfeasible(NetworkXError): ...
class NetworkXNoPath(NetworkXUnfeasible): ...
class NetworkXNoCycle(NetworkXUnfeasible): ...
class NetworkXUnbounded(NetworkXError): ...
class NetworkXNotImplemented(NetworkXError): ...
class NodeNotFound(NetworkXError): ...
class HasACycle(NetworkXError): ...
class PowerIterationFailedConvergence(NetworkXError): ...

# ---------------------------------------------------------------------------
# View objects
# ---------------------------------------------------------------------------

class NodeView:
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, n: Any) -> dict[str, Any]: ...
    def __bool__(self) -> bool: ...
    def __call__(
        self, data: Union[bool, str, None] = None, default: Any = None
    ) -> "NodeView": ...

class EdgeView:
    def __len__(self) -> int: ...
    def __contains__(self, edge: tuple[Any, Any]) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, edge: tuple[Any, Any]) -> dict[str, Any]: ...
    def __bool__(self) -> bool: ...
    def __call__(
        self,
        data: Union[bool, str, None] = None,
        nbunch: Any = None,
        default: Any = None,
    ) -> Any: ...

class DegreeView:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[Any, int]]: ...
    def __getitem__(self, n: Any) -> int: ...
    def __bool__(self) -> bool: ...

class AdjacencyView:
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __getitem__(self, n: Any) -> dict[Any, dict[str, Any]]: ...
    def __iter__(self) -> Iterator: ...
    def __bool__(self) -> bool: ...

# ---------------------------------------------------------------------------
# DiGraph view objects
# ---------------------------------------------------------------------------

class DiNodeView:
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, n: Any) -> dict[str, Any]: ...
    def __bool__(self) -> bool: ...
    def __call__(
        self, data: Union[bool, str, None] = None, default: Any = None
    ) -> "DiNodeView": ...

class DiEdgeView:
    def __len__(self) -> int: ...
    def __contains__(self, edge: tuple[Any, Any]) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, edge: tuple[Any, Any]) -> dict[str, Any]: ...
    def __bool__(self) -> bool: ...
    def __call__(
        self,
        data: Union[bool, str, None] = None,
        nbunch: Any = None,
        default: Any = None,
    ) -> Any: ...

class DiDegreeView:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[Any, int]]: ...
    def __getitem__(self, n: Any) -> int: ...
    def __bool__(self) -> bool: ...

class DiAdjacencyView:
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __getitem__(self, n: Any) -> dict[Any, dict[str, Any]]: ...
    def __iter__(self) -> Iterator: ...
    def __bool__(self) -> bool: ...

# ---------------------------------------------------------------------------
# Graph class
# ---------------------------------------------------------------------------

class Graph:
    graph: dict[str, Any]
    nodes: NodeView
    edges: EdgeView
    degree: DegreeView
    adj: AdjacencyView
    name: str

    def __init__(
        self, incoming_graph_data: Any = None, **attr: Any
    ) -> None: ...
    def is_directed(self) -> bool: ...
    def is_multigraph(self) -> bool: ...
    def number_of_nodes(self) -> int: ...
    def order(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def size(self, weight: Optional[str] = None) -> float: ...
    def add_node(self, n: Any, **attr: Any) -> None: ...
    def add_nodes_from(self, nodes_for_adding: Any, **attr: Any) -> None: ...
    def remove_node(self, n: Any) -> None: ...
    def remove_nodes_from(self, nodes: Any) -> None: ...
    def add_edge(self, u: Any, v: Any, **attr: Any) -> None: ...
    def add_edges_from(self, ebunch_to_add: Any, **attr: Any) -> None: ...
    def add_weighted_edges_from(
        self, ebunch_to_add: Any, weight: str = "weight"
    ) -> None: ...
    def remove_edge(self, u: Any, v: Any) -> None: ...
    def remove_edges_from(self, ebunch: Any) -> None: ...
    def clear(self) -> None: ...
    def clear_edges(self) -> None: ...
    def has_node(self, n: Any) -> bool: ...
    def has_edge(self, u: Any, v: Any) -> bool: ...
    def neighbors(self, n: Any) -> list[Any]: ...
    def adjacency(self) -> list[tuple[Any, list[Any]]]: ...
    def copy(self) -> "Graph": ...
    def subgraph(self, nodes: Any) -> "Graph": ...
    def edge_subgraph(self, edges: Any) -> "Graph": ...
    def to_undirected(self) -> "Graph": ...
    def to_directed(self) -> None: ...
    def update(
        self, edges: Any = None, nodes: Any = None
    ) -> None: ...
    def number_of_edges_between(
        self, u: Any = None, v: Any = None
    ) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, n: Any) -> dict[Any, dict[str, Any]]: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __copy__(self) -> "Graph": ...
    def __deepcopy__(self, memo: Any = None) -> "Graph": ...

# ---------------------------------------------------------------------------
# DiGraph class
# ---------------------------------------------------------------------------

class DiGraph:
    graph: dict[str, Any]
    nodes: DiNodeView
    edges: DiEdgeView
    degree: DiDegreeView
    in_degree: DiDegreeView
    out_degree: DiDegreeView
    adj: DiAdjacencyView
    succ: DiAdjacencyView
    pred: DiAdjacencyView
    name: str

    def __init__(
        self, incoming_graph_data: Any = None, **attr: Any
    ) -> None: ...
    def is_directed(self) -> bool: ...
    def is_multigraph(self) -> bool: ...
    def number_of_nodes(self) -> int: ...
    def order(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def size(self, weight: Optional[str] = None) -> float: ...
    def add_node(self, n: Any, **attr: Any) -> None: ...
    def add_nodes_from(self, nodes_for_adding: Any, **attr: Any) -> None: ...
    def remove_node(self, n: Any) -> None: ...
    def remove_nodes_from(self, nodes: Any) -> None: ...
    def add_edge(self, u: Any, v: Any, **attr: Any) -> None: ...
    def add_edges_from(self, ebunch_to_add: Any, **attr: Any) -> None: ...
    def add_weighted_edges_from(
        self, ebunch_to_add: Any, weight: str = "weight"
    ) -> None: ...
    def remove_edge(self, u: Any, v: Any) -> None: ...
    def remove_edges_from(self, ebunch: Any) -> None: ...
    def clear(self) -> None: ...
    def clear_edges(self) -> None: ...
    def has_node(self, n: Any) -> bool: ...
    def has_edge(self, u: Any, v: Any) -> bool: ...
    def neighbors(self, n: Any) -> list[Any]: ...
    def successors(self, n: Any) -> list[Any]: ...
    def predecessors(self, n: Any) -> list[Any]: ...
    def adjacency(self) -> list[tuple[Any, list[Any]]]: ...
    def reverse(self) -> "DiGraph": ...
    def copy(self) -> "DiGraph": ...
    def subgraph(self, nodes: Any) -> "DiGraph": ...
    def edge_subgraph(self, edges: Any) -> "DiGraph": ...
    def to_undirected(self) -> Graph: ...
    def to_directed(self) -> "DiGraph": ...
    def update(
        self, edges: Any = None, nodes: Any = None
    ) -> None: ...
    def number_of_edges_between(
        self, u: Any = None, v: Any = None
    ) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, n: Any) -> dict[Any, dict[str, Any]]: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __copy__(self) -> "DiGraph": ...
    def __deepcopy__(self, memo: Any = None) -> "DiGraph": ...

# ---------------------------------------------------------------------------
# Algorithm functions — shortest path
# ---------------------------------------------------------------------------

def shortest_path(
    g: Graph,
    source: Any = None,
    target: Any = None,
    weight: Optional[str] = None,
    method: str = "dijkstra",
) -> Any: ...

def shortest_path_length(
    g: Graph,
    source: Any,
    target: Any,
    weight: Optional[str] = None,
) -> Any: ...

def has_path(g: Graph, source: Any, target: Any) -> bool: ...

def average_shortest_path_length(
    g: Graph, weight: Optional[str] = None
) -> float: ...

def dijkstra_path(
    g: Graph, source: Any, target: Any, weight: str = "weight"
) -> list[Any]: ...

def bellman_ford_path(
    g: Graph, source: Any, target: Any, weight: str = "weight"
) -> list[Any]: ...

def multi_source_dijkstra(
    g: Graph, sources: Any, weight: str = "weight"
) -> tuple[dict[Any, float], dict[Any, list[Any]]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — connectivity
# ---------------------------------------------------------------------------

def is_connected(g: Graph) -> bool: ...
def connected_components(g: Graph) -> list[list[Any]]: ...
def number_connected_components(g: Graph) -> int: ...
def node_connectivity(g: Graph) -> int: ...
def minimum_node_cut(g: Graph) -> list[Any]: ...
def edge_connectivity(g: Graph, capacity: str = "capacity") -> float: ...
def articulation_points(g: Graph) -> list[Any]: ...
def bridges(g: Graph) -> list[tuple[Any, Any]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — centrality
# ---------------------------------------------------------------------------

def degree_centrality(g: Graph) -> dict[Any, float]: ...
def closeness_centrality(g: Graph) -> dict[Any, float]: ...
def harmonic_centrality(g: Graph) -> dict[Any, float]: ...
def katz_centrality(g: Graph) -> dict[Any, float]: ...
def betweenness_centrality(g: Graph) -> dict[Any, float]: ...
def edge_betweenness_centrality(g: Graph) -> dict[tuple[Any, Any], float]: ...
def eigenvector_centrality(g: Graph) -> dict[Any, float]: ...
def pagerank(g: Graph) -> dict[Any, float]: ...
def hits(g: Graph) -> tuple[dict[Any, float], dict[Any, float]]: ...
def average_neighbor_degree(g: Graph) -> dict[Any, float]: ...
def degree_assortativity_coefficient(g: Graph) -> float: ...
def voterank(g: Graph) -> list[Any]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — clustering
# ---------------------------------------------------------------------------

def clustering(g: Graph) -> dict[Any, float]: ...
def average_clustering(g: Graph) -> float: ...
def transitivity(g: Graph) -> float: ...
def triangles(g: Graph) -> dict[Any, int]: ...
def square_clustering(g: Graph) -> dict[Any, float]: ...
def find_cliques(g: Graph) -> list[list[Any]]: ...
def graph_clique_number(g: Graph) -> int: ...

# ---------------------------------------------------------------------------
# Algorithm functions — matching
# ---------------------------------------------------------------------------

def maximal_matching(g: Graph) -> list[tuple[Any, Any]]: ...
def max_weight_matching(
    g: Graph, weight: str = "weight"
) -> list[tuple[Any, Any]]: ...
def min_weight_matching(
    g: Graph, weight: str = "weight"
) -> list[tuple[Any, Any]]: ...
def min_edge_cover(g: Graph) -> list[tuple[Any, Any]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — flow
# ---------------------------------------------------------------------------

def maximum_flow_value(
    g: Graph, source: Any, sink: Any, capacity: str = "capacity"
) -> float: ...
def minimum_cut_value(
    g: Graph, source: Any, sink: Any, capacity: str = "capacity"
) -> float: ...

# ---------------------------------------------------------------------------
# Algorithm functions — distance measures
# ---------------------------------------------------------------------------

def density(g: Graph) -> float: ...
def eccentricity(g: Graph) -> dict[Any, int]: ...
def diameter(g: Graph) -> int: ...
def radius(g: Graph) -> int: ...
def center(g: Graph) -> list[Any]: ...
def periphery(g: Graph) -> list[Any]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — tree, forest, bipartite, coloring, core
# ---------------------------------------------------------------------------

def is_tree(g: Graph) -> bool: ...
def is_forest(g: Graph) -> bool: ...
def is_bipartite(g: Graph) -> bool: ...
def bipartite_sets(g: Graph) -> tuple[list[Any], list[Any]]: ...
def greedy_color(g: Graph) -> dict[Any, int]: ...
def core_number(g: Graph) -> dict[Any, int]: ...
def minimum_spanning_tree(g: Graph, weight: str = "weight") -> Graph: ...

# ---------------------------------------------------------------------------
# Algorithm functions — Euler
# ---------------------------------------------------------------------------

def is_eulerian(g: Graph) -> bool: ...
def has_eulerian_path(g: Graph) -> bool: ...
def is_semieulerian(g: Graph) -> bool: ...
def eulerian_circuit(
    g: Graph, source: Any = None
) -> list[tuple[Any, Any]]: ...
def eulerian_path(
    g: Graph, source: Any = None
) -> list[tuple[Any, Any]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — paths and cycles
# ---------------------------------------------------------------------------

def all_shortest_paths(
    g: Graph | DiGraph,
    source: Any,
    target: Any,
    weight: Optional[str] = None,
    method: Optional[str] = None,
) -> list[list[Any]]: ...
def all_simple_paths(
    g: Graph, source: Any, target: Any, cutoff: Optional[int] = None
) -> list[list[Any]]: ...
def cycle_basis(
    g: Graph, root: Any = None
) -> list[list[Any]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — graph operators
# ---------------------------------------------------------------------------

def complement(g: Graph | DiGraph) -> Graph | DiGraph: ...

# ---------------------------------------------------------------------------
# Algorithm functions — efficiency
# ---------------------------------------------------------------------------

def global_efficiency(g: Graph) -> float: ...
def local_efficiency(g: Graph) -> float: ...

# ---------------------------------------------------------------------------
# Graph generators — classic
# ---------------------------------------------------------------------------

def empty_graph(n: int = 0) -> Graph: ...
def path_graph(n: int) -> Graph: ...
def cycle_graph(n: int) -> Graph: ...
def star_graph(n: int) -> Graph: ...
def complete_graph(n: int) -> Graph: ...

# ---------------------------------------------------------------------------
# Graph generators — random
# ---------------------------------------------------------------------------

def gnp_random_graph(n: int, p: float, seed: int) -> Graph: ...
def watts_strogatz_graph(n: int, k: int, p: float, seed: int) -> Graph: ...
def barabasi_albert_graph(n: int, m: int, seed: int) -> Graph: ...

# ---------------------------------------------------------------------------
# Traversal — BFS
# ---------------------------------------------------------------------------

def bfs_edges(
    g: Union[Graph, DiGraph],
    source: Any,
    reverse: bool = False,
    depth_limit: Optional[int] = None,
    sort_neighbors: Optional[Any] = None,
) -> list[tuple[Any, Any]]: ...
def bfs_tree(
    g: Union[Graph, DiGraph],
    source: Any,
    reverse: bool = False,
    depth_limit: Optional[int] = None,
    sort_neighbors: Optional[Any] = None,
) -> DiGraph: ...
def bfs_predecessors(
    g: Union[Graph, DiGraph],
    source: Any,
    depth_limit: Optional[int] = None,
    sort_neighbors: Optional[Any] = None,
) -> list[tuple[Any, Any]]: ...
def bfs_successors(
    g: Union[Graph, DiGraph],
    source: Any,
    depth_limit: Optional[int] = None,
    sort_neighbors: Optional[Any] = None,
) -> list[tuple[Any, list[Any]]]: ...
def bfs_layers(
    g: Union[Graph, DiGraph],
    sources: Any,
) -> list[list[Any]]: ...
def descendants_at_distance(
    g: Union[Graph, DiGraph],
    source: Any,
    distance: int,
) -> set[Any]: ...

# ---------------------------------------------------------------------------
# Traversal — DFS
# ---------------------------------------------------------------------------

def dfs_edges(
    g: Union[Graph, DiGraph],
    source: Optional[Any] = None,
    depth_limit: Optional[int] = None,
) -> list[tuple[Any, Any]]: ...
def dfs_tree(
    g: Union[Graph, DiGraph],
    source: Any,
    depth_limit: Optional[int] = None,
) -> DiGraph: ...
def dfs_predecessors(
    g: Union[Graph, DiGraph],
    source: Any,
    depth_limit: Optional[int] = None,
) -> dict[Any, Any]: ...
def dfs_successors(
    g: Union[Graph, DiGraph],
    source: Any,
    depth_limit: Optional[int] = None,
) -> dict[Any, list[Any]]: ...
def dfs_preorder_nodes(
    g: Union[Graph, DiGraph],
    source: Optional[Any] = None,
    depth_limit: Optional[int] = None,
) -> list[Any]: ...
def dfs_postorder_nodes(
    g: Union[Graph, DiGraph],
    source: Optional[Any] = None,
    depth_limit: Optional[int] = None,
) -> list[Any]: ...

# ---------------------------------------------------------------------------
# DAG algorithms
# ---------------------------------------------------------------------------

def topological_sort(g: DiGraph) -> list[Any]: ...
def topological_generations(g: DiGraph) -> list[list[Any]]: ...
def dag_longest_path(g: DiGraph) -> list[Any]: ...
def dag_longest_path_length(g: DiGraph) -> int: ...
def lexicographic_topological_sort(g: DiGraph) -> list[Any]: ...
def is_directed_acyclic_graph(g: Union[Graph, DiGraph]) -> bool: ...
def ancestors(g: DiGraph, source: Any) -> frozenset[Any]: ...
def descendants(g: DiGraph, source: Any) -> frozenset[Any]: ...

# ---------------------------------------------------------------------------
# All shortest paths
# ---------------------------------------------------------------------------

def all_shortest_paths(
    g: Union[Graph, DiGraph],
    source: Any,
    target: Any,
    weight: Optional[str] = None,
    method: Optional[str] = None,
) -> list[list[Any]]: ...

# ---------------------------------------------------------------------------
# Complement
# ---------------------------------------------------------------------------

def complement(g: Union[Graph, DiGraph]) -> Union[Graph, DiGraph]: ...

# ---------------------------------------------------------------------------
# Reciprocity
# ---------------------------------------------------------------------------

def overall_reciprocity(g: DiGraph) -> float: ...
def reciprocity(
    g: DiGraph,
    nodes: Optional[Any] = None,
) -> Union[float, dict[Any, float]]: ...

# ---------------------------------------------------------------------------
# Wiener index
# ---------------------------------------------------------------------------

def wiener_index(g: Graph) -> float: ...

# ---------------------------------------------------------------------------
# Link prediction
# ---------------------------------------------------------------------------

def common_neighbors(g: Graph, u: Any, v: Any) -> list[Any]: ...

def jaccard_coefficient(
    g: Graph,
    ebunch: Optional[list[tuple[Any, Any]]] = None,
) -> list[tuple[Any, Any, float]]: ...

def adamic_adar_index(
    g: Graph,
    ebunch: Optional[list[tuple[Any, Any]]] = None,
) -> list[tuple[Any, Any, float]]: ...

def preferential_attachment(
    g: Graph,
    ebunch: Optional[list[tuple[Any, Any]]] = None,
) -> list[tuple[Any, Any, float]]: ...

def resource_allocation_index(
    g: Graph,
    ebunch: Optional[list[tuple[Any, Any]]] = None,
) -> list[tuple[Any, Any, float]]: ...

# ---------------------------------------------------------------------------
# Graph metrics
# ---------------------------------------------------------------------------

def average_degree_connectivity(g: Graph) -> dict[int, float]: ...

# ---------------------------------------------------------------------------
# Strongly connected components
# ---------------------------------------------------------------------------

def strongly_connected_components(g: DiGraph) -> list[list[Any]]: ...
def number_strongly_connected_components(g: DiGraph) -> int: ...
def is_strongly_connected(g: DiGraph) -> bool: ...

# ---------------------------------------------------------------------------
# Weakly connected components
# ---------------------------------------------------------------------------

def weakly_connected_components(g: DiGraph) -> list[list[Any]]: ...
def number_weakly_connected_components(g: DiGraph) -> int: ...
def is_weakly_connected(g: DiGraph) -> bool: ...

# ---------------------------------------------------------------------------
# Transitive closure / reduction
# ---------------------------------------------------------------------------

def transitive_closure(g: DiGraph) -> DiGraph: ...
def transitive_reduction(g: DiGraph) -> DiGraph: ...

# ---------------------------------------------------------------------------
# Dominating set
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Single-source shortest paths
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Graph predicates & utilities
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# All-pairs shortest paths
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Maximum spanning tree
# ---------------------------------------------------------------------------

def maximum_spanning_tree(g: Graph, weight: str = "weight") -> Graph: ...

# ---------------------------------------------------------------------------
# Condensation
# ---------------------------------------------------------------------------

def condensation(g: DiGraph) -> tuple[DiGraph, dict[Any, int]]: ...

def all_pairs_shortest_path(
    g: Graph,
    cutoff: Optional[int] = None,
) -> dict[Any, dict[Any, list[Any]]]: ...
def all_pairs_shortest_path_length(
    g: Graph,
    cutoff: Optional[int] = None,
) -> dict[Any, dict[Any, int]]: ...

def is_empty(g: Union[Graph, DiGraph]) -> bool: ...
def non_neighbors(g: Graph, v: Any) -> list[Any]: ...
def number_of_cliques(g: Graph) -> dict[Any, int]: ...

def single_source_shortest_path(
    g: Graph,
    source: Any,
    cutoff: Optional[int] = None,
) -> dict[Any, list[Any]]: ...
def single_source_shortest_path_length(
    g: Graph,
    source: Any,
    cutoff: Optional[int] = None,
) -> dict[Any, int]: ...

# ---------------------------------------------------------------------------
# Dominating set
# ---------------------------------------------------------------------------

def dominating_set(g: Graph) -> list[Any]: ...
def is_dominating_set(g: Graph, nbunch: Any) -> bool: ...
def rich_club_coefficient(g: Graph) -> dict[int, float]: ...
def s_metric(g: Graph) -> float: ...

# ---------------------------------------------------------------------------
# Graph isomorphism
# ---------------------------------------------------------------------------

def is_isomorphic(g1: Graph, g2: Graph) -> bool: ...
def could_be_isomorphic(g1: Graph, g2: Graph) -> bool: ...
def fast_could_be_isomorphic(g1: Graph, g2: Graph) -> bool: ...
def faster_could_be_isomorphic(g1: Graph, g2: Graph) -> bool: ...

# ---------------------------------------------------------------------------
# A* shortest path
# ---------------------------------------------------------------------------

def astar_path(
    g: Graph,
    source: Any,
    target: Any,
    heuristic: Optional[Any] = None,
    weight: str = "weight",
) -> list[Any]: ...
def astar_path_length(
    g: Graph,
    source: Any,
    target: Any,
    heuristic: Optional[Any] = None,
    weight: str = "weight",
) -> float: ...
def shortest_simple_paths(
    g: Graph,
    source: Any,
    target: Any,
    weight: Optional[str] = None,
) -> list[list[Any]]: ...

# ---------------------------------------------------------------------------
# Approximation algorithms
# ---------------------------------------------------------------------------

def min_weighted_vertex_cover(g: Graph, weight: Optional[str] = None) -> set[Any]: ...
def maximum_independent_set(g: Graph) -> set[Any]: ...
def max_clique(g: Graph) -> set[Any]: ...
def clique_removal(g: Graph) -> tuple[set[Any], list[set[Any]]]: ...
def large_clique_size(g: Graph) -> int: ...

# ---------------------------------------------------------------------------
# Planarity
# ---------------------------------------------------------------------------

def is_planar(g: Graph) -> bool: ...

# ---------------------------------------------------------------------------
# Distance measures — barycenter
# ---------------------------------------------------------------------------

def barycenter(g: Graph) -> list[Any]: ...

# ---------------------------------------------------------------------------
# Community detection
# ---------------------------------------------------------------------------

def louvain_communities(
    g: Graph,
    resolution: float = 1.0,
    weight: str = "weight",
    seed: Optional[int] = None,
) -> list[list[Any]]: ...
def modularity(
    g: Graph,
    communities: list[list[str]],
    resolution: float = 1.0,
    weight: str = "weight",
) -> float: ...
def label_propagation_communities(g: Graph) -> list[list[Any]]: ...
def greedy_modularity_communities(
    g: Graph,
    resolution: float = 1.0,
    weight: str = "weight",
) -> list[list[Any]]: ...

# ---------------------------------------------------------------------------
# Graph operators
# ---------------------------------------------------------------------------

def union(g: Graph, h: Graph) -> Graph: ...
def intersection(g: Graph, h: Graph) -> Graph: ...
def compose(g: Graph, h: Graph) -> Graph: ...
def difference(g: Graph, h: Graph) -> Graph: ...
def symmetric_difference(g: Graph, h: Graph) -> Graph: ...
def degree_histogram(g: Graph) -> list[int]: ...

# ---------------------------------------------------------------------------
# Tree recognition
# ---------------------------------------------------------------------------

def is_arborescence(g: Union[Graph, DiGraph]) -> bool: ...
def is_branching(g: Union[Graph, DiGraph]) -> bool: ...

# ---------------------------------------------------------------------------
# Isolates
# ---------------------------------------------------------------------------

def is_isolate(g: Union[Graph, DiGraph], node: Any) -> bool: ...
def isolates(g: Union[Graph, DiGraph]) -> list[Any]: ...
def number_of_isolates(g: Union[Graph, DiGraph]) -> int: ...

# ---------------------------------------------------------------------------
# Boundary
# ---------------------------------------------------------------------------

def edge_boundary(
    g: Union[Graph, DiGraph],
    nbunch1: list[Any],
    nbunch2: Optional[list[Any]] = None,
) -> list[tuple[Any, Any]]: ...
def node_boundary(
    g: Union[Graph, DiGraph],
    nbunch1: list[Any],
    nbunch2: Optional[list[Any]] = None,
) -> list[Any]: ...

# ---------------------------------------------------------------------------
# Path validation
# ---------------------------------------------------------------------------

def is_simple_path(g: Union[Graph, DiGraph], path: list[Any]) -> bool: ...

# ---------------------------------------------------------------------------
# Matching validators
# ---------------------------------------------------------------------------

def is_matching(g: Graph, matching: list[tuple[Any, Any]]) -> bool: ...
def is_maximal_matching(g: Graph, matching: list[tuple[Any, Any]]) -> bool: ...
def is_perfect_matching(g: Graph, matching: list[tuple[Any, Any]]) -> bool: ...

# ---------------------------------------------------------------------------
# Cycle detection
# ---------------------------------------------------------------------------

def simple_cycles(g: DiGraph) -> list[list[Any]]: ...
def find_cycle(g: Union[Graph, DiGraph]) -> list[tuple[Any, Any]]: ...
def girth(g: Graph) -> Optional[int]: ...
def find_negative_cycle(
    g: Graph, source: Any, weight: str = "weight"
) -> list[Any]: ...

# ---------------------------------------------------------------------------
# Graph predicates
# ---------------------------------------------------------------------------

def is_graphical(sequence: list[int]) -> bool: ...
def is_digraphical(sequence: list[tuple[int, int]]) -> bool: ...
def is_multigraphical(sequence: list[int]) -> bool: ...
def is_pseudographical(sequence: list[int]) -> bool: ...
def is_regular(g: Graph) -> bool: ...
def is_k_regular(g: Graph, k: int) -> bool: ...
def is_tournament(g: DiGraph) -> bool: ...
def is_weighted(g: Graph, weight: str = "weight") -> bool: ...
def is_negatively_weighted(g: Graph, weight: str = "weight") -> bool: ...
def is_path(g: Graph) -> bool: ...
def is_distance_regular(g: Graph) -> bool: ...

# ---------------------------------------------------------------------------
# DAG algorithms — additional
# ---------------------------------------------------------------------------

def edge_bfs(g: Union[Graph, DiGraph], source: Any) -> list[tuple[Any, Any]]: ...
def edge_dfs(g: Union[Graph, DiGraph], source: Any) -> list[tuple[Any, Any]]: ...

def is_edge_cover(g: Graph, edges: Any) -> bool: ...
def max_weight_clique(g: Graph, weight: str = "weight") -> tuple[list[Any], float]: ...

def is_aperiodic(g: DiGraph) -> bool: ...
def antichains(g: DiGraph) -> list[list[Any]]: ...
def immediate_dominators(g: DiGraph, start: Any) -> dict[Any, Any]: ...
def dominance_frontiers(g: DiGraph, start: Any) -> dict[Any, set[Any]]: ...

# ---------------------------------------------------------------------------
# Additional shortest path algorithms
# ---------------------------------------------------------------------------

def dijkstra_path_length(g: Union[Graph, DiGraph], source: Any, target: Any, weight: str = "weight") -> float: ...
def bellman_ford_path_length(g: Union[Graph, DiGraph], source: Any, target: Any, weight: str = "weight") -> float: ...
def single_source_dijkstra(g: Graph, source: Any, weight: str = "weight") -> tuple[dict[Any, float], dict[Any, list[Any]]]: ...
def single_source_dijkstra_path(g: Graph, source: Any, weight: str = "weight") -> dict[Any, list[Any]]: ...
def single_source_dijkstra_path_length(g: Graph, source: Any, weight: str = "weight") -> dict[Any, float]: ...
def single_source_bellman_ford(g: Graph, source: Any, weight: str = "weight") -> tuple[dict[Any, float], dict[Any, list[Any]]]: ...
def single_source_bellman_ford_path(g: Graph, source: Any, weight: str = "weight") -> dict[Any, list[Any]]: ...
def single_source_bellman_ford_path_length(g: Graph, source: Any, weight: str = "weight") -> dict[Any, float]: ...
def single_target_shortest_path(g: Graph, target: Any, cutoff: Optional[int] = None) -> dict[Any, list[Any]]: ...
def single_target_shortest_path_length(g: Graph, target: Any, cutoff: Optional[int] = None) -> dict[Any, int]: ...
def all_pairs_dijkstra_path(g: Graph, weight: str = "weight") -> dict[Any, dict[Any, list[Any]]]: ...
def all_pairs_dijkstra_path_length(g: Graph, weight: str = "weight") -> dict[Any, dict[Any, float]]: ...
def all_pairs_bellman_ford_path(g: Graph, weight: str = "weight") -> dict[Any, dict[Any, list[Any]]]: ...
def all_pairs_bellman_ford_path_length(g: Graph, weight: str = "weight") -> dict[Any, dict[Any, float]]: ...
def floyd_warshall(g: Graph, weight: str = "weight") -> dict[Any, dict[Any, float]]: ...
def floyd_warshall_predecessor_and_distance(g: Graph, weight: str = "weight") -> tuple[dict[Any, dict[Any, list[Any]]], dict[Any, dict[Any, float]]]: ...
def bidirectional_shortest_path(g: Graph, source: Any, target: Any) -> list[Any]: ...
def negative_edge_cycle(g: Graph, weight: str = "weight") -> bool: ...
def predecessor(g: Graph, source: Any, cutoff: Optional[int] = None) -> dict[Any, list[Any]]: ...
def path_weight(g: Union[Graph, DiGraph], path: list[Any], weight: str = "weight") -> float: ...

# ---------------------------------------------------------------------------
# Additional centrality algorithms
# ---------------------------------------------------------------------------

def in_degree_centrality(g: DiGraph) -> dict[Any, float]: ...
def out_degree_centrality(g: DiGraph) -> dict[Any, float]: ...
def local_reaching_centrality(g: Union[Graph, DiGraph], v: Any) -> float: ...
def global_reaching_centrality(g: Union[Graph, DiGraph]) -> float: ...
def group_degree_centrality(g: Graph, s: Any) -> float: ...
def group_in_degree_centrality(g: DiGraph, s: Any) -> float: ...
def group_out_degree_centrality(g: DiGraph, s: Any) -> float: ...

# ---------------------------------------------------------------------------
# Component algorithms
# ---------------------------------------------------------------------------

def node_connected_component(g: Graph, n: Any) -> list[Any]: ...
def is_biconnected(g: Graph) -> bool: ...
def biconnected_components(g: Graph) -> list[list[Any]]: ...
def biconnected_component_edges(g: Graph) -> list[list[tuple[Any, Any]]]: ...
def is_semiconnected(g: DiGraph) -> bool: ...
def kosaraju_strongly_connected_components(g: DiGraph) -> list[list[Any]]: ...
def attracting_components(g: DiGraph) -> list[list[Any]]: ...
def number_attracting_components(g: DiGraph) -> int: ...
def is_attracting_component(g: DiGraph, component: Any) -> bool: ...

# ---------------------------------------------------------------------------
# Read/write — graph I/O
# ---------------------------------------------------------------------------

from typing import IO, Any, Union
from os import PathLike

def read_edgelist(path: Union[str, PathLike, IO[str]]) -> Graph: ...
def write_edgelist(g: Union[Graph, DiGraph], path: Union[str, PathLike, IO[str]]) -> None: ...
def read_adjlist(path: Union[str, PathLike, IO[str]]) -> Graph: ...
def write_adjlist(g: Union[Graph, DiGraph], path: Union[str, PathLike, IO[str]]) -> None: ...
def node_link_data(g: Union[Graph, DiGraph]) -> dict[str, Any]: ...
def node_link_graph(data: dict[str, Any]) -> Graph: ...
def read_graphml(path: Union[str, PathLike, IO[str]]) -> Graph: ...
def write_graphml(g: Union[Graph, DiGraph], path: Union[str, PathLike, IO[str]]) -> None: ...
